import os

CASSANDRA_HOST = os.environ['CASSANDRA_HOST']
CASSANDRA_PORT = os.environ['CASSANDRA_PORT']
CASSANDRA_KEYSPACE = os.environ['CASSANDRA_KEYSPACE']
CASSANDRA_USERNAME = os.environ['CASSANDRA_USERNAME']
CASSANDRA_PASSWORD = os.environ['CASSANDRA_PASSWORD']

N_PEOPLE = os.environ['N_PEOPLE']

