version: '3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - FDSnet
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u",
          "cassandra",
          "-p",
          "cassandra",
          "-e",
          "describe cluster"
        ]
      interval: 30s
      timeout: 10s
      retries: 5

  dataloader:
    container_name: dataloader
    build:
      context: ./dataloader
      dockerfile: Dockerfile
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - FDSnet

networks:
  FDSnet:
    driver: bridge
