version: '3'
services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    networks:
      - FDSnet
    healthcheck:
      test:
        [
          "CMD",
          "cqlsh",
          "-u",
          "cassandra",
          "-p",
          "cassandra",
          "-e",
          "describe cluster"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    mem_limit: 5g

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - FDSnet

  dataloader:
    container_name: dataloader
    build:
      context: ./dataloader
      dockerfile: Dockerfile
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - FDSnet

  sasmock:
    container_name: sasmock
    build:
      context: ./sasmock
      dockerfile: Dockerfile
    depends_on:
      dataloader:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    networks:
      - FDSnet

networks:
  FDSnet:
    driver: bridge
