version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
    networks:
      - fds-network
    ports:
      - 6379:6379

  translator:
    build: ./translator
    container_name: translator
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./translator/.env
    volumes:
      - ./translator:/app/
    networks:
      - fds-network
    ports:
      - 8000:8000
    depends_on:
      - redis


#######################

networks:
  fds-network:
    driver: bridge

volumes:
  cache:
    driver: local