version: '3.8'

services:
  cache:
    image: redis:alpine
    networks:
      - fds-network
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

networks:
  fds-network:
    driver: bridge

volumes:
  cache:
    driver: local