version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - fds-network
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./redis:/data

  translator:
    build: ./translator
    container_name: translator
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - CLEAR_CACHE=false
    healthcheck:
      test: curl -f translator:8000/healthcheck || exit 1
    env_file:
      - ./translator/.env
    networks:
      - fds-network
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - redis
    volumes:
      - ./translator:/app/

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    networks:
      - fds-network
    ports:
      - 9042:9042
    volumes:
      - ./cassandra/data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 15s
      timeout: 10s
      retries: 10

  # sasmock:
  #   build: ./sasmock
  #   container_name: sasmock
  #   command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
  #   environment:
  #     - N_PEOPLE=100
  #   healthcheck:
  #     test: curl -f sasmock:8001/healthcheck || exit 1
  #   env_file:
  #     - ./sasmock/.env
  #   networks:
  #     - fds-network
  #   ports:
  #     - 8001:8001
  #   restart: always
  #   depends_on:
  #     - cassandra
  #   volumes:
  #     - ./translator:/app/

  cassandra-load-keyspace:
    image: cassandra:latest
    container_name: cassandra-load-keyspace
    environment:
      - "ERASE_DATA=false"
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra/scripts:/scripts
    entrypoint: ["sh", "/scripts/init.sh"]
    restart: "no"
    networks:
      - fds-network

  # data-loader:
  #   build:
  #     context: ./data-loader
  #     dockerfile: Dockerfile
  #   container_name: data-loader
  #   command: python3 app/main.py
  #   environment:
  #     - "DOCKER=true"
  #     - "BASE_LANG=es"
  #     - "LOAD_DISEASES=false"
  #   depends_on:
  #     cassandra-load-keyspace:
  #       condition: service_completed_successfully
  #     translator:
  #       condition: service_healthy
  #   env_file:
  #     - ./data-loader/.env
  #   networks:
  #     - fds-network


#######################

networks:
  fds-network:
    driver: bridge

volumes:
  cache:
    driver: local