version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - fds-network
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-commander
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #     - HTTP_USER=admin
  #     - HTTP_PASSWORD=admin
  #   networks:
  #     - fds-network
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - redis

networks:
  fds-network:
    driver: bridge

volumes:
  cache:
    driver: local