# sudo apt-get update
# sudo apt-get install libcurl4-openssl-dev
# sudo apt-get install libjpeg-dev
# sudo apt-get install libsodium-devel
# sudo apt-get install udunits2-devel
# sudo apt-get install libgdal-dev
# sudo yum install proj-devel

